import os
import smtplib
from dotenv import load_dotenv
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
from datetime import datetime

# Load environment variables from .env file
load_dotenv()

# Email details
sender_email = "bryanwi09@gmail.com"  # Replace with your Gmail address
receiver_email = "bryanwi09@gmail.com"  # Replace with the recipient's email address
subject = "NBA Player Stats"
body = "Attached is the CSV file containing all NBA player stats for the 2023/2024 season"

# Load app password from .env file
app_password = os.getenv("GMAIL_APP_PASSWORD")

# Create a multipart message and set headers
message = MIMEMultipart()
message["From"] = sender_email
message["To"] = receiver_email
message["Subject"] = subject

# Add body to email
message.attach(MIMEText(body, "plain"))

# Attachment file (CSV generated by the previous script)
current_date = datetime.now().strftime("%Y%m%d")
filename = f'nba_player_game_stats_{current_date}.csv'  # This should match the filename used in the nba_api script

# Open the file in binary mode
try:
    with open(filename, "rb") as attachment:
        part = MIMEApplication(attachment.read(), Name=os.path.basename(filename))
    # After the file is closed
    part['Content-Disposition'] = f'attachment; filename= {os.path.basename(filename)}'
    message.attach(part)
except FileNotFoundError:
    print(f"Could not find the file '{filename}'. Please check the file path.")

# Create a secure SSL context and send the email
try:
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender_email, app_password)
        server.sendmail(sender_email, receiver_email, message.as_string())
    print("Email sent successfully!")
except Exception as e:
    print(f"Error sending email: {e}")
